/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all events
         * @description Retrieves a list of all calendar events
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of calendar events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarEvent"][];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a new event
         * @description Creates a new calendar event
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEventDto"];
                };
            };
            responses: {
                /** @description The created event */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarEvent"];
                    };
                };
                /** @description Missing required fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get event by ID
         * @description Retrieves a single calendar event by its ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The event ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The calendar event */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarEvent"];
                    };
                };
                /** @description Event not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * Update an event
         * @description Updates an existing calendar event
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The event ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEventDto"];
                };
            };
            responses: {
                /** @description The updated event */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarEvent"];
                    };
                };
                /** @description Event not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete an event
         * @description Deletes a calendar event
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The event ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Event not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CalendarEvent: {
            /**
             * @description Unique identifier for the event
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Title of the event
             * @example Team Meeting
             */
            title: string;
            /**
             * Format: date-time
             * @description Start time in ISO 8601 format
             * @example 2024-01-15T09:00:00.000Z
             */
            start: string;
            /**
             * Format: date-time
             * @description End time in ISO 8601 format
             * @example 2024-01-15T10:00:00.000Z
             */
            end: string;
            /**
             * @description Color for the event display
             * @example #3b82f6
             */
            color: string;
        };
        CreateEventDto: {
            /**
             * @description Title of the event
             * @example Team Meeting
             */
            title: string;
            /**
             * Format: date-time
             * @description Start time in ISO 8601 format
             * @example 2024-01-15T09:00:00.000Z
             */
            start: string;
            /**
             * Format: date-time
             * @description End time in ISO 8601 format
             * @example 2024-01-15T10:00:00.000Z
             */
            end: string;
            /**
             * @description Color for the event display
             * @example #3b82f6
             */
            color: string;
        };
        UpdateEventDto: {
            /**
             * @description Title of the event
             * @example Updated Meeting
             */
            title?: string;
            /**
             * Format: date-time
             * @description Start time in ISO 8601 format
             * @example 2024-01-15T09:00:00.000Z
             */
            start?: string;
            /**
             * Format: date-time
             * @description End time in ISO 8601 format
             * @example 2024-01-15T10:00:00.000Z
             */
            end?: string;
            /**
             * @description Color for the event display
             * @example #3b82f6
             */
            color?: string;
        };
        Error: {
            /**
             * @description Error message
             * @example Event not found
             */
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
